# Site Settings
title: Anton Kerschbaum-Gruber - Curriculum Vitae
url: 'http://anton.kerschbaum-gruber.net'
baseurl: '/' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Anton Kerschbaum-Gruber
tagline: Software &amp; Data Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Coming soon.'

#sidebar links
email: anton+www@kerschbaum-gruber.net
#phone: private
website: anton.kerschbaum-gruber.net #do not add http://
linkedin: akerschbaum
github: jives
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
include: [".well-known"]